import express from 'express'
import {z} from 'zod'
import {randomUUID} from 'node:crypto'
import {rankAgents,type ActivityHint,type Agent,type Trade} from '../domain'
import {Repository} from './repository'
import {DreamDexAdapter} from './dreamdex'

const registration=z.object({name:z.string().trim().min(2).max(60),description:z.string().trim().min(10).max(500),builder:z.string().trim().min(2).max(80),markets:z.array(z.enum(['BTC','ETH'])).min(1),windows:z.array(z.enum(['15M','1H'])).min(1),integration:z.string().url().max(300),walletAddress:z.string().regex(/^0x[0-9a-fA-F]{40}$/)})
const activityHint=z.object({txHash:z.string().regex(/^0x[0-9a-fA-F]{64}$/),orderId:z.string().min(1).optional(),marketId:z.string().regex(/^0x[0-9a-fA-F]{64}$/).optional()})
const roundRegistration=z.object({name:z.string().trim().min(3).max(100),marketId:z.string().regex(/^0x[0-9a-fA-F]{64}$/),market:z.enum(['BTC','ETH']),window:z.enum(['15M','1H']),opensAt:z.string().datetime(),closesAt:z.string().datetime()}).refine(value=>Date.parse(value.closesAt)>Date.parse(value.opensAt),{message:'Round must close after it opens'})
const roundStatus=z.object({status:z.enum(['registration','open','closed','settling','finalized'])})

export function createApp(repo=new Repository()){
 const app=express(),dreamdex=new DreamDexAdapter();app.use(express.json({limit:'32kb'}))
 app.get('/api/health',(_q,r)=>r.json({ok:true,dreamdex:dreamdex.status()}))
 app.get('/api/state',(_q,r)=>{const agents=repo.listAgents(),trades=repo.listTrades();r.json({agents,trades,rounds:repo.listRounds(),activityHints:repo.listActivityHints(),ranked:rankAgents(agents,trades),dreamdex:dreamdex.status()})})
 app.post('/api/agents',(q,r)=>{const parsed=registration.safeParse(q.body);if(!parsed.success)return r.status(400).json({error:'Invalid registration',issues:parsed.error.issues});const agent:Agent={...parsed.data,walletAddress:parsed.data.walletAddress as `0x${string}`,id:randomUUID(),createdAt:new Date().toISOString()};try{return r.status(201).json(repo.createAgent(agent))}catch{return r.status(409).json({error:'Agent name already registered'})}})
 app.get('/api/agents/:id',(q,r)=>{const agent=repo.getAgent(q.params.id);if(!agent)return r.status(404).json({error:'Agent not found'});const trades=repo.listTrades().filter(t=>t.agentId===agent.id);return r.json({agent,performance:rankAgents([agent],trades)[0],trades})})
 app.post('/api/agents/:id/activity',(q,r)=>{const agent=repo.getAgent(q.params.id);if(!agent)return r.status(404).json({error:'Agent not found'});const parsed=activityHint.safeParse(q.body);if(!parsed.success)return r.status(400).json({error:'Invalid activity hint',issues:parsed.error.issues});const hint:ActivityHint={id:randomUUID(),agentId:agent.id,txHash:parsed.data.txHash as `0x${string}`,orderId:parsed.data.orderId,marketId:parsed.data.marketId as `0x${string}`|undefined,status:'pending',createdAt:new Date().toISOString()};try{return r.status(202).json(repo.createActivityHint(hint))}catch{return r.status(409).json({error:'Activity already submitted'})}})
 app.get('/api/agents/:id/activity',async(q,r)=>{const agent=repo.getAgent(q.params.id);if(!agent)return r.status(404).json({error:'Agent not found'});try{const [orders,portfolio,settlements]=await Promise.all([dreamdex.ordersForAgent(agent.id,agent.walletAddress),dreamdex.portfolioForAgent(agent.walletAddress),dreamdex.settlementsForAgent(agent.walletAddress)]);const hints=repo.listActivityHints(agent.id);for(const hint of hints.filter(h=>h.status==='pending'))repo.markActivityHint(hint.id,orders.some(order=>order.txHash.toLowerCase()===hint.txHash.toLowerCase())?'verified':'rejected');return r.json({agentId:agent.id,walletAddress:agent.walletAddress,orders,portfolio,settlements,hints:repo.listActivityHints(agent.id),authoritative:'DreamDEX indexer',metricsStatus:settlements.some(settlement=>settlement.status==='resolved'||settlement.status==='voided')?'settlement evidence available':'settlement pending'})}catch(error){return r.status(503).json({error:error instanceof Error?error.message:'DreamDEX verification unavailable'})}})
 app.post('/api/settlements',(_q,r)=>r.status(410).json({error:'Client-submitted settlements are disabled. CLASH derives results from verified DreamDEX activity.'}))
 app.post('/api/rounds',(q,r)=>{const parsed=roundRegistration.safeParse(q.body);if(!parsed.success)return r.status(400).json({error:'Invalid round',issues:parsed.error.issues});try{return r.status(201).json(repo.createRound({...parsed.data,marketId:parsed.data.marketId as `0x${string}`,id:randomUUID(),status:'registration',createdAt:new Date().toISOString()}))}catch{return r.status(409).json({error:'Round could not be created'})}})
 app.post('/api/rounds/:id/participants',(q,r)=>{const round=repo.getRound(q.params.id),agent=repo.getAgent(String(q.body?.agentId??''));if(!round)return r.status(404).json({error:'Round not found'});if(!agent)return r.status(404).json({error:'Agent not found'});if(round.status!=='registration')return r.status(409).json({error:'Round registration is closed'});if(!agent.markets.includes(round.market)||!agent.windows.includes(round.window))return r.status(409).json({error:'Agent does not support this market/window'});try{return r.status(201).json(repo.joinRound(round.id,agent.id))}catch{return r.status(409).json({error:'Agent already joined'})}})
 app.patch('/api/rounds/:id',(q,r)=>{if(!repo.getRound(q.params.id))return r.status(404).json({error:'Round not found'});const parsed=roundStatus.safeParse(q.body);if(!parsed.success)return r.status(400).json({error:'Invalid status'});return r.json(repo.updateRoundStatus(q.params.id,parsed.data.status))})
 app.post('/api/rounds/:roundId/agents/:agentId/sync',async(q,r)=>{const round=repo.getRound(q.params.roundId),agent=repo.getAgent(q.params.agentId);if(!round)return r.status(404).json({error:'Round not found'});if(!agent)return r.status(404).json({error:'Agent not found'});if(!round.participants.includes(agent.id))return r.status(409).json({error:'Agent is not registered for this round'});if(round.status==='registration'||round.status==='open')return r.status(409).json({error:'Round has not closed'});try{const performance=await dreamdex.settledPerformance(agent.walletAddress,round.marketId);if(!performance)return r.status(202).json({status:'pending',message:'No unambiguous settled DreamDEX performance is available yet'});const existing=repo.getTradeByReference(performance.reference);if(existing)return r.json({status:'already-recorded',trade:existing});const trade:Trade={id:randomUUID(),agentId:agent.id,roundId:round.id,market:round.market,direction:performance.direction,result:performance.result,pnl:performance.pnl,timestamp:new Date(Number(performance.timestamp)*1000).toISOString(),reference:performance.reference};repo.createTrade(trade);return r.status(201).json({status:'recorded',trade,source:'DreamDEX fills + market resolution + SDK position PnL'})}catch(error){return r.status(503).json({error:error instanceof Error?error.message:'Settlement verification unavailable'})}})
 app.get('/api/dreamdex/markets',async(_q,r)=>{try{return r.json({status:dreamdex.status(),markets:await dreamdex.discover()})}catch(error){return r.status(503).json({status:dreamdex.status(),error:error instanceof Error?error.message:'DreamDEX unavailable'})}})
 return app
}
