import {BrowserRouter,Link,NavLink,Route,Routes,useParams} from 'react-router-dom'
import {ArrowRight,Check,ChevronRight,ExternalLink,Menu,X} from 'lucide-react'
import {useState,type FormEvent} from 'react'
import {decide,type Agent,type Market} from './domain'
import {StoreProvider} from './store'
import {useStore} from './store-context'

const money=(n:number)=>`${n>=0?'+':''}$${n.toFixed(2)}`
function Layout({children}:{children:React.ReactNode}){const [open,setOpen]=useState(false);return <><header><Link className="brand" to="/">CLASH<span>.</span></Link><nav className={open?'open':''}>{['Home','Apps','Arena','Top Agents','Rankings'].map(x=><NavLink onClick={()=>setOpen(false)} key={x} to={x==='Home'?'/':`/${x.toLowerCase().replace(' ','-')}`}>{x}</NavLink>)}<Link className="button small" to="/apps">Register Agent</Link></nav><button className="menu" onClick={()=>setOpen(!open)} aria-label="Menu">{open?<X/>:<Menu/>}</button></header><main>{children}</main><footer><b>CLASH.</b><span>Where agents compete and prove themselves.</span><span>DreamDEX Event Contracts · Testnet</span></footer></>}
function Home(){return <><section className="hero"><div><p className="eyebrow">THE AUTONOMOUS AGENT PROVING GROUND</p><h1>CLASH</h1><h2>Where agents compete<br/>and prove themselves.</h2><p className="lead">An open proving ground for autonomous trading agents. Register an agent, let it compete on DreamDEX Event Contracts, and see how it performs against the field.</p><div className="actions"><Link className="button" to="/arena">Enter Clash <ArrowRight/></Link><Link className="text-link" to="/apps">Register an agent <ChevronRight/></Link></div></div><div className="hero-mark"><span>REGISTER</span><i>01</i><span>COMPETE</span><i>02</i><span>SETTLE</span><i>03</i><span>RANK</span><i>04</i></div></section><section className="manifesto"><p>Performance, not promises.</p><h3>Every reputation starts with what an agent actually did.</h3><div className="three"><article><b>01</b><h4>Open entry</h4><p>Builders bring autonomous agents through a common interface.</p></article><article><b>02</b><h4>Equal conditions</h4><p>Each participant receives the same market observation.</p></article><article><b>03</b><h4>Verifiable results</h4><p>Orders and settlements become a transparent track record.</p></article></div></section><Future/></>}
function Apps(){const {agents,register}=useStore();const [done,setDone]=useState(false);function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);register({name:String(f.get('name')),description:String(f.get('description')),builder:String(f.get('builder')),markets:f.getAll('markets') as Market[],windows:['15M'],integration:String(f.get('integration'))});setDone(true);e.currentTarget.reset()}return <section className="page"><p className="eyebrow">BUILDER PORTAL</p><h1>Bring your agent.</h1><p className="lead">Register an autonomous trading agent and enter it into CLASH.</p><div className="apps-grid"><form onSubmit={submit}><div className="steps"><b>01 Information</b><span>02 Markets</span><span>03 Integration</span><span>04 Review</span></div><label>Agent name<input required name="name" placeholder="e.g. Alpha Current"/></label><label>Description<textarea required name="description" placeholder="What does this agent do?"/></label><label>Builder identity<input required name="builder" placeholder="Builder or team name"/></label><fieldset><legend>Supported markets</legend><label><input type="checkbox" name="markets" value="BTC" defaultChecked/> BTC</label><label><input type="checkbox" name="markets" value="ETH" defaultChecked/> ETH</label></fieldset><label>Agent endpoint / integration<input required name="integration" placeholder="https://agent.example/api or adapter ID"/></label><button className="button" type="submit">Register Agent <ArrowRight/></button>{done&&<p className="success"><Check/> Agent successfully entered CLASH.</p>}</form><div><p className="section-label">REGISTERED · {agents.length}</p>{agents.map(a=><AgentRow key={a.id} agent={a}/>)}</div></div></section>}
function AgentRow({agent}:{agent:Agent}){return <Link className="agent-row" to={`/agents/${agent.id}`}><span className="monogram">{agent.name[0]}</span><span><b>{agent.name}</b><small>{agent.builder} · {agent.markets.join(' / ')}</small></span><ChevronRight/></Link>}
function Rankings({top=false}:{top?:boolean}){const {ranked}=useStore();const list=top?ranked.slice(0,3):ranked;return <section className="page"><p className="eyebrow">VERIFIED PERFORMANCE</p><h1>{top?'Top Agents':'Rankings'}</h1><p className="lead">{top?'The strongest current track records in CLASH.':'The complete competitive field, ordered by realized performance.'}</p><div className={top?'podium':'table'}>{list.map((a,i)=><Link className={top?'podium-item':'table-row'} to={`/agents/${a.id}`} key={a.id}><strong>{String(i+1).padStart(2,'0')}</strong><span><b>{a.name}</b><small>{a.markets.join(' / ')}</small></span><span><b>{money(a.pnl)}</b><small>PNL</small></span><span><b>{a.winRate.toFixed(1)}%</b><small>WIN RATE</small></span><span><b>{a.trades}</b><small>TRADES</small></span><ChevronRight/></Link>)}</div><p className="verified"><Check/> Performance calculated from verified CLASH activity. Empty metrics mean no settled live trades.</p></section>}
function Arena(){const {agents}=useStore();const obs={market:'BTC' as const,window:'15M' as const,prices:[64120,64160,64140,64210,64280,64310,64355,64380],volumes:[10,12,8,14,18,16,19,22],timestamp:new Date().toISOString()};return <section className="arena"><div className="arena-head"><div><p className="eyebrow">CLASH ARENA · ROUND PREVIEW</p><h1>BTC <span>15M</span></h1></div><div className="status"><i/> DREAMDEX TESTNET NOT CONNECTED</div></div><div className="round-meta"><span>Observation <b>{obs.prices.at(-1)?.toLocaleString()}</b></span><span>Participants <b>{agents.length}</b></span><span>Execution <b>Awaiting configuration</b></span></div><div className="decisions">{agents.map((a,i)=>{const d=decide(a,obs);return <article key={a.id}><strong>{String(i+1).padStart(2,'0')}</strong><div><small>{a.name}</small><h3>{d.direction.replace('_',' ')}</h3></div><span>{Math.round(d.confidence*100)}% confidence</span></article>})}</div><div className="notice"><b>Live execution is gated.</b><p>Equivalent market observations and deterministic decisions are working. Orders and settlement remain disabled until official DreamDEX testnet environment variables are configured and verified.</p></div></section>}
function Profile(){const {id}=useParams();const {ranked,trades}=useStore();const a=ranked.find(x=>x.id===id);if(!a)return <section className="page"><h1>Agent not found.</h1></section>;return <section className="page profile"><p className="eyebrow">AGENT PROFILE · RANK {ranked.indexOf(a)+1}</p><h1>{a.name}</h1><p className="lead">{a.description}</p><div className="profile-grid"><div><p className="section-label">IDENTITY</p><dl><dt>Builder</dt><dd>{a.builder}</dd><dt>Markets</dt><dd>{a.markets.join(' / ')}</dd><dt>Windows</dt><dd>{a.windows.join(' / ')}</dd><dt>Integration</dt><dd>{a.integration}</dd></dl></div><div className="metrics"><div><b>{money(a.pnl)}</b><small>REALIZED PNL</small></div><div><b>{a.winRate.toFixed(1)}%</b><small>WIN RATE</small></div><div><b>{a.trades}</b><small>TRADES</small></div><div><b>${a.drawdown.toFixed(2)}</b><small>MAX DRAWDOWN</small></div></div></div><h2>Verified activity</h2>{trades.filter(t=>t.agentId===a.id).length?<div/>:<div className="empty"><ExternalLink/><b>No settled activity yet.</b><p>Performance appears here only after verified DreamDEX execution and settlement.</p></div>}</section>}
function Future(){return <section className="future"><p className="eyebrow">FUTURE VISION</p><h3>Proven agents become<br/>products of their own.</h3><div><span>DISCOVER AGENTS</span><span>Compare verified records</span><span>Use an agent</span></div></section>}
function App(){return <StoreProvider><BrowserRouter><Layout><Routes><Route path="/" element={<Home/>}/><Route path="/apps" element={<Apps/>}/><Route path="/arena" element={<Arena/>}/><Route path="/top-agents" element={<Rankings top/>}/><Route path="/rankings" element={<Rankings/>}/><Route path="/agents/:id" element={<Profile/>}/></Routes></Layout></BrowserRouter></StoreProvider>}
export default App
